package com.sweetsound.cardinfo.constant

class ConstShardPreference {
    companion object {
        val SHARED_PREF_FIRST_RUNNING = "SHARED_PREF_FIRST_RUNNING"
        val KEY_FIRST_RUNNING = "KEY_FIRST_RUNNING"

        val SHARED_PREF_REACHED_USAGE_AMOUNT = "SHARED_PREF_REACHED_USAGE_AMOUNT"
        val KEY_WOORI_CARD_REACHED_USAGE_AMOUNT = "KEY_WOORI_CARD_REACHED_USAGE_AMOUNT"
        val KEY_KB_CARD_REACHED_USAGE_AMOUNT = "KEY_KB_CARD_REACHED_USAGE_AMOUNT"
        val KEY_HANA_CARD_REACHED_USAGE_AMOUNT = "KEY_HANA_CARD_REACHED_USAGE_AMOUNT"
        val KEY_HYUNDAI_CARD_REACHED_USAGE_AMOUNT = "KEY_HYUNDAI_CARD_REACHED_USAGE_AMOUNT"

        val SHARED_PREF_AUTO_LOGIN = "SHARED_PREF_AUTO_LOGIN"
        val KEY_EMAIL = "KEY_EMAIL"
        val KEY_PASSWD = "KEY_PASSWD"

        val SHARED_PREF_LOGIN_EMAIL = "SHARED_PREF_LOGIN_EMAIL"
    }
}